### ISSUE TITLE
Integrate skale-contracts into the upgrade script

### ISSUE THREAD

**Issue by DimaStebaev** [skalenetwork/skale-manager#1006]
```[tasklist]
### Tasks
- [ ] https://github.com/skalenetwork/skale-manager/issues/1005
- [ ] https://github.com/skalenetwork/upgrade-tools/issues/222
- [ ] https://github.com/skalenetwork/skale-manager/issues/1062
```

**Comment by DimaStebaev** [comment]
Waiting for a start of Release 2.3 development stage.
